### ISSUE TITLE
Collaboration

### ISSUE THREAD

**Issue by RubenJ01** [gaborszita/discord-genius-bot-bot#3]
Hey!

Do you have a discord where I could reach you for collaboration on a project?
If you're interested feel free to add me: RubenJ01#0001

**Comment by gaborszita** [comment]
I added you, I'm OtherCards#7157.Sent from my Galaxy
-------- Original message --------From: Ruben Eekhof ***@***.***> Date: 7/18/22  1:56 PM  (GMT-08:00) To: gaborszita/discord-genius-bot-bot ***@***.***> Cc: Subscribed ***@***.***> Subject: [gaborszita/discord-genius-bot-bot] Collaboration (Issue #3) 
Hey!
Do you have a discord where I could reach you for collaboration on a project?
If you're interested feel free to add me: RubenJ01#0001
